### ISSUE TITLE
Random Warning in Chunk Tick

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#29]
### Spark link

https://spark.lucko.me/SM7caU5M6x

### Stack trace

```
[14:18:38 WARN]: java.lang.IllegalStateException: Previous state should be 0, not 1
[14:18:38 WARN]:        at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader$PlayerChunkLoaderData.updateQueues(RegionizedPlayerChunkLoader.java:680)
[14:18:38 WARN]:        at ca.spottedleaf.moonrise.patches.chunk_system.player.RegionizedPlayerChunkLoader.tick(RegionizedPlayerChunkLoader.java:313)
[14:18:38 WARN]:        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:405)
[14:18:38 WARN]:        at net.minecraft.server.level.ServerLevel.endTick$tickChunks(ServerLevel.java:765)
[14:18:38 WARN]:        at net.minecraft.server.level.ServerLevel.lambda$tick$11(ServerLevel.java:1117)
[14:18:38 WARN]:        at net.minecraft.server.level.ServerLevel.runWorld(ServerLevel.java:836)
[14:18:38 WARN]:        at me.dueris.canvas.thread.WorldTickThread.run(WorldTickThread.java:19)

```

### Canvas version

Current Purpur Version: 1.21-DEV-fdbdc43 (MC: 1.21)*
* You are running the latest version
Previous: 1.21-DEV-c8a38cd (MC: 1.21)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

### Other

Plugins: None
Client: 1.21

**Comment by Dueris** [comment]
ah shit not this again

**Comment by TheDeafCreeper** [comment]
A familiar issue I see

**Comment by Dueris** [comment]
came up before when in beta testing of having chunk ticks on the world tickers instead of the main thread

**Comment by Dueris** [comment]
fixed
