### ISSUE TITLE
Kick at 3800 TPS

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#32]
### Spark link

N/A

### Stack trace

```
[20:18:06 ERROR]: Failed to handle packet for /127.0.0.1:37122
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:974) ~[?:1.21-DEV-29f8121]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:360) ~[?:1.21-DEV-29f8121]
        at net.minecraft.network.Connection.tick(Connection.java:664) ~[?:1.21-DEV-29f8121]
        at net.minecraft.server.level.ServerLevel.lambda$tick$11(ServerLevel.java:932) ~[?:1.21-DEV-29f8121]
        at net.minecraft.server.level.ServerLevel.runWorld(ServerLevel.java:836) ~[?:1.21-DEV-29f8121]
        at me.dueris.canvas.thread.WorldTickThread.run(WorldTickThread.java:19) ~[?:1.21-DEV-29f8121]
Caused by: java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:143) ~[?:?]
        at net.minecraft.world.entity.Entity.getOnPos(Entity.java:1387) ~[?:1.21-DEV-29f8121]
        at net.minecraft.world.entity.Entity.getOnPosLegacy(Entity.java:1374) ~[?:1.21-DEV-29f8121]
        at net.minecraft.world.entity.Entity.spawnSprintParticle(Entity.java:2012) ~[?:1.21-DEV-29f8121]
        at net.minecraft.world.entity.Entity.baseTick(Entity.java:911) ~[?:1.21-DEV-29f8121]
        at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:447) ~[?:1.21-DEV-29f8121]
        at net.minecraft.world.entity.Entity.tick(Entity.java:882) ~[?:1.21-DEV-29f8121]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3222) ~[?:1.21-DEV-29f8121]
        at net.minecraft.world.entity.player.Player.tick(Player.java:317) ~[?:1.21-DEV-29f8121]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:888) ~[?:1.21-DEV-29f8121]
        ... 5 more
```

### Actions to reproduce (if known)

Set TPS really high
Run around

### Canvas version

Current Purpur Version: 1.21-DEV-29f8121 (MC: 1.21)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

### Other

idk if this is worth fixing.

**Comment by Dueris** [comment]
when not uncapping the tps does this occur?
