### ISSUE TITLE
Redstone bug

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#34]
### Spark link

https://spark.lucko.me/0p1XArxnP7

### Stack trace

```
[02:33:34 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 6
[02:33:34 WARN]:        at net.minecraft.world.level.redstone.CollectingNeighborUpdater$MultiNeighborUpdate.runNext(CollectingNeighborUpdater.java:145)
[02:33:34 WARN]:        at net.minecraft.world.level.redstone.CollectingNeighborUpdater.lambda$runUpdates$0(CollectingNeighborUpdater.java:86)
[02:33:34 WARN]:        at net.minecraft.world.level.redstone.CollectingNeighborUpdater.lambda$runUpdates$1(CollectingNeighborUpdater.java:111)
[02:33:34 WARN]:        at java.base/java.util.concurrent.ConcurrentLinkedDeque.bulkRemove(ConcurrentLinkedDeque.java:1633)
[02:33:34 WARN]:        at java.base/java.util.concurrent.ConcurrentLinkedDeque.removeIf(ConcurrentLinkedDeque.java:1607)
[02:33:34 WARN]:        at net.minecraft.world.level.redstone.CollectingNeighborUpdater.runUpdates(CollectingNeighborUpdater.java:110)
[02:33:34 WARN]:        at net.minecraft.world.level.redstone.CollectingNeighborUpdater.addAndRun(CollectingNeighborUpdater.java:69)
[02:33:34 WARN]:        at net.minecraft.world.level.redstone.CollectingNeighborUpdater.updateNeighborsAtExceptFromFacing(CollectingNeighborUpdater.java:50)
[02:33:34 WARN]:        at net.minecraft.server.level.ServerLevel.updateNeighborsAt(ServerLevel.java:2109)
[02:33:34 WARN]:        at net.minecraft.server.level.ServerLevel.blockUpdated(ServerLevel.java:2682)
[02:33:34 WARN]:        at net.minecraft.world.level.Level.notifyAndUpdatePhysics(Level.java:808)
[02:33:34 WARN]:        at net.minecraft.world.level.Level.setBlock(Level.java:780)
[02:33:34 WARN]:        at net.minecraft.world.level.Level.setBlock(Level.java:694)
[02:33:34 WARN]:        at net.minecraft.world.level.material.FlowingFluid.spreadTo(FlowingFluid.java:307)
[02:33:34 WARN]:        at net.minecraft.world.level.material.FlowingFluid.spreadToSides(FlowingFluid.java:192)
[02:33:34 WARN]:        at net.minecraft.world.level.material.FlowingFluid.spread(FlowingFluid.java:157)
[02:33:34 WARN]:        at net.minecraft.world.level.material.FlowingFluid.tick(FlowingFluid.java:508)
[02:33:34 WARN]:        at net.minecraft.world.level.material.FluidState.tick(FluidState.java:78)
[02:33:34 WARN]:        at net.minecraft.server.level.ServerLevel.tickFluid(ServerLevel.java:1598)
[02:33:34 WARN]:        at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:197)
[02:33:34 WARN]:        at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:94)
[02:33:34 WARN]:        at net.minecraft.server.level.ServerLevel.lambda$tick$11(ServerLevel.java:1036)
[02:33:34 WARN]:        at net.minecraft.server.level.ServerLevel.runWorld(ServerLevel.java:836)
[02:33:34 WARN]:        at me.dueris.canvas.thread.WorldTickThread.run(WorldTickThread.java:19)
```

### Actions to reproduce (if known)

Attempt to build a simple redstone clock (2 repeaters facing opposite directions, connected with redstone)

### Canvas version

Current Purpur Version: 1.21-DEV-301ceab (MC: 1.21)*
* You are running the latest version
Previous: 1.21-DEV-29f8121 (MC: 1.21)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

**Comment by Dueris** [comment]
fixed
