### ISSUE TITLE
ALREADY CONTAINED error

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#38]
### Spark link

N/A

### Stack trace

```
[19:00:32 ERROR]: Illegal ChunkMap::addEntity for world world: FallingBlockEntity['Falling Sand'/334731, uuid='3d9a363d-da1a-4aa1-8853-8bfca962a4a5', l='ServerLevel[world]', x=509.50, y=63.00, z=319.50, cpos=[31, 19], tl=0, v=true] ALREADY CONTAINED (This would have crashed your server)
java.lang.Throwable: null
        at net.minecraft.server.level.ChunkMap.addEntity(ChunkMap.java:888) ~[?:1.21-DEV-6fb9cf2]
        at net.minecraft.server.level.ServerChunkCache.addEntity(ServerChunkCache.java:617) ~[?:1.21-DEV-6fb9cf2]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2945) ~[?:1.21-DEV-6fb9cf2]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2881) ~[?:1.21-DEV-6fb9cf2]
        at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup.entityStatusChange(EntityLookup.java:287) ~[?:1.21-DEV-6fb9cf2]
        at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup.lambda$entityStatusChange$0(EntityLookup.java:255) ~[?:1.21-DEV-6fb9cf2]
        at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
        at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
        at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup.entityStatusChange(EntityLookup.java:340) ~[?:1.21-DEV-6fb9cf2]
        at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:256) ~[?:1.21-DEV-6fb9cf2]
        at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup.chunkStatusChange(EntityLookup.java:347) ~[?:1.21-DEV-6fb9cf2]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.changeEntityChunkStatus(NewChunkHolder.java:1230) ~[?:1.21-DEV-6fb9cf2]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1315) ~[?:1.21-DEV-6fb9cf2]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1345) ~[?:1.21-DEV-6fb9cf2]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1329) ~[?:1.21-DEV-6fb9cf2]
        at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1284) ~[?:1.21-DEV-6fb9cf2]
        at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:348) ~[?:1.21-DEV-6fb9cf2]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:718) ~[?:1.21-DEV-6fb9cf2]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:344) ~[?:1.21-DEV-6fb9cf2]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1680) ~[?:1.21-DEV-6fb9cf2]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1662) ~[?:1.21-DEV-6fb9cf2]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:145) ~[?:1.21-DEV-6fb9cf2]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1620) ~[?:1.21-DEV-6fb9cf2]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1628) ~[?:1.21-DEV-6fb9cf2]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1468) ~[?:1.21-DEV-6fb9cf2]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[?:1.21-DEV-6fb9cf2]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Actions to reproduce (if known)

lots of TNT

### Canvas version

Current Purpur Version: 1.21-DEV-6fb9cf2 (MC: 1.21)*
* You are running the latest version
Previous: 1.21-DEV-e7b957c (MC: 1.21)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

**Comment by Dueris** [comment]
fixed
