### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#43]
### Spark link

N/A

### Stack trace

```
[15:09:35 ERROR]: Entity threw exception at world:302.73026477001804,64.0,82.22362688814994
java.util.ConcurrentModificationException: null
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095) ~[?:?]
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049) ~[?:?]
        at net.minecraft.world.level.EntityGetter.getNearestEntity(EntityGetter.java:230) ~[?:1.21-DEV-314373e]
        at net.minecraft.world.level.EntityGetter.getNearestPlayer(EntityGetter.java:208) ~[?:1.21-DEV-314373e]
        at net.minecraft.world.entity.ai.goal.target.NearestAttackableTargetGoal.findTarget(NearestAttackableTargetGoal.java:100) ~[?:1.21-DEV-314373e]
        at net.minecraft.world.entity.ai.goal.target.NearestAttackableTargetGoal.canUse(NearestAttackableTargetGoal.java:85) ~[?:1.21-DEV-314373e]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.canUse(WrappedGoal.java:22) ~[?:1.21-DEV-314373e]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:105) ~[?:1.21-DEV-314373e]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:971) ~[?:1.21-DEV-314373e]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3560) ~[?:1.21-DEV-314373e]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:714) ~[?:1.21-DEV-314373e]
        at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:45) ~[?:1.21-DEV-314373e]
        at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:308) ~[?:1.21-DEV-314373e]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3263) ~[?:1.21-DEV-314373e]
        at net.minecraft.world.entity.Mob.tick(Mob.java:475) ~[?:1.21-DEV-314373e]
        at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:301) ~[?:1.21-DEV-314373e]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1657) ~[?:1.21-DEV-314373e]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1485) ~[?:1.21-DEV-314373e]
        at net.minecraft.server.level.ServerLevel.lambda$tick$9(ServerLevel.java:1108) ~[?:1.21-DEV-314373e]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:41) ~[?:1.21-DEV-314373e]
        at net.minecraft.server.level.ServerLevel.lambda$tick$10(ServerLevel.java:1087) ~[?:1.21-DEV-314373e]
        at net.minecraft.server.level.ServerLevel.runWorld(ServerLevel.java:844) ~[?:1.21-DEV-314373e]
        at me.dueris.canvas.thread.WorldTickThread.run(WorldTickThread.java:19) ~[?:1.21-DEV-314373e]

```

### Actions to reproduce (if known)

Have lots of players join

### Canvas version

Current Canvas Version: 1.21-DEV-314373e (MC: 1.21)*
* You are 13 version(s) behind
Download the new version at: https://canvas.kesug.com/downloads
Previous: 1.21-DEV-6fb9cf2 (MC: 1.21)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

### Other

There were also 2 more warnings that I believe are related:
```
[15:09:32 WARN]: java.util.ConcurrentModificationException
[15:09:32 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095)
[15:09:32 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049)
[15:09:32 WARN]:        at net.minecraft.world.level.EntityGetter.getNearestPlayer(EntityGetter.java:128)
[15:09:32 WARN]:        at net.minecraft.world.level.EntityGetter.findNearbyPlayer(EntityGetter.java:120)
[15:09:32 WARN]:        at net.minecraft.world.entity.Mob.checkDespawn(Mob.java:917)
[15:09:32 WARN]:        at net.minecraft.server.level.ServerLevel.lambda$tick$9(ServerLevel.java:1094)
[15:09:32 WARN]:        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:41)
[15:09:32 WARN]:        at net.minecraft.server.level.ServerLevel.lambda$tick$10(ServerLevel.java:1087)
[15:09:32 WARN]:        at net.minecraft.server.level.ServerLevel.runWorld(ServerLevel.java:844)
[15:09:32 WARN]:        at me.dueris.canvas.thread.WorldTickThread.run(WorldTickThread.java:19)
```

```
[15:09:32 WARN]: java.util.ConcurrentModificationException
[15:09:32 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095)
[15:09:32 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049)
[15:09:32 WARN]:        at net.minecraft.world.level.EntityGetter.getNearestPlayer(EntityGetter.java:128)
[15:09:32 WARN]:        at net.minecraft.world.level.EntityGetter.getNearestPlayer(EntityGetter.java:171)
[15:09:32 WARN]:        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:257)
[15:09:32 WARN]:        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:208)
[15:09:32 WARN]:        at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:178)
[15:09:32 WARN]:        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:498)
[15:09:32 WARN]:        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:406)
[15:09:32 WARN]:        at net.minecraft.server.level.ServerLevel.endTick$tickChunks(ServerLevel.java:782)
[15:09:32 WARN]:        at net.minecraft.server.level.ServerLevel.lambda$tick$10(ServerLevel.java:1125)
[15:09:32 WARN]:        at net.minecraft.server.level.ServerLevel.runWorld(ServerLevel.java:844)
[15:09:32 WARN]:        at me.dueris.canvas.thread.WorldTickThread.run(WorldTickThread.java:19)
```

**Comment by Dueris** [comment]
related to prev issue
