### ISSUE TITLE
Entity Spawner ConcurrentModificationError

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#44]
### Spark link

N/A

### Stack trace

```
[19:46:10 WARN]: java.util.ConcurrentModificationException
[19:46:10 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095)
[19:46:10 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049)
[19:46:10 WARN]:        at net.minecraft.world.level.EntityGetter.getNearestPlayer(EntityGetter.java:128)
[19:46:10 WARN]:        at net.minecraft.world.level.EntityGetter.getNearestPlayer(EntityGetter.java:171)
[19:46:10 WARN]:        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForPosition(NaturalSpawner.java:257)
[19:46:10 WARN]:        at net.minecraft.world.level.NaturalSpawner.spawnCategoryForChunk(NaturalSpawner.java:208)
[19:46:10 WARN]:        at net.minecraft.world.level.NaturalSpawner.spawnForChunk(NaturalSpawner.java:178)
[19:46:10 WARN]:        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:505)
[19:46:10 WARN]:        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:413)
[19:46:10 WARN]:        at net.minecraft.server.level.ServerLevel.endTick$tickChunks(ServerLevel.java:782)
[19:46:10 WARN]:        at net.minecraft.server.level.ServerLevel.lambda$tick$10(ServerLevel.java:1125)
[19:46:10 WARN]:        at net.minecraft.server.level.ServerLevel.runWorld(ServerLevel.java:844)
[19:46:10 WARN]:        at me.dueris.canvas.thread.WorldTickThread.run(WorldTickThread.java:19)
```

### Actions to reproduce (if known)

Seems to happen randomly, mainly when a player joins?

### Canvas version

Current Canvas Version: 1.21-DEV-7dfc70c (MC: 1.21)*
* You are running the latest version
Previous: 1.21-DEV-01a622a (MC: 1.21)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

**Comment by Dueris** [comment]
should also be fixed now
