### ISSUE TITLE
ActivationRange ConcurrentModificationError

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#45]
### Spark link

N/A

### Stack trace

```
[19:47:30 WARN]: java.util.ConcurrentModificationException
[19:47:30 WARN]:        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095)
[19:47:30 WARN]:        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049)
[19:47:30 WARN]:        at org.spigotmc.ActivationRange.activateEntities(ActivationRange.java:196)
[19:47:30 WARN]:        at net.minecraft.server.level.ServerLevel.lambda$tick$10(ServerLevel.java:1084)
[19:47:30 WARN]:        at net.minecraft.server.level.ServerLevel.runWorld(ServerLevel.java:844)
[19:47:30 WARN]:        at me.dueris.canvas.thread.WorldTickThread.run(WorldTickThread.java:19)
```

### Actions to reproduce (if known)

Same as #44 

### Canvas version

Current Canvas Version: 1.21-DEV-7dfc70c (MC: 1.21)*
* You are running the latest version
Previous: 1.21-DEV-01a622a (MC: 1.21)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

**Comment by Dueris** [comment]
fixed
