### ISSUE TITLE
Error after going through nether portal

### ISSUE THREAD

**Issue by TheDeafCreeper** [Dueris/Canvas#46]
### Spark link

https://spark.lucko.me/aC3px6DToZ

### Stack trace

```
[19:52:40 ERROR]: Failed to handle packet for /127.0.0.1:37235
net.minecraft.ReportedException: Ticking player
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:974) ~[?:1.21-DEV-7dfc70c]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:360) ~[?:1.21-DEV-7dfc70c]
        at net.minecraft.network.Connection.tick(Connection.java:667) ~[?:1.21-DEV-7dfc70c]
        at net.minecraft.server.level.ServerLevel.lambda$tick$10(ServerLevel.java:940) ~[?:1.21-DEV-7dfc70c]
        at net.minecraft.server.level.ServerLevel.runWorld(ServerLevel.java:844) ~[?:1.21-DEV-7dfc70c]
        at me.dueris.canvas.thread.WorldTickThread.run(WorldTickThread.java:19) ~[?:1.21-DEV-7dfc70c]
Caused by: java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:143) ~[?:?]
        at net.minecraft.world.entity.Entity.getOnPos(Entity.java:1449) ~[?:1.21-DEV-7dfc70c]
        at net.minecraft.world.entity.Entity.getOnPos(Entity.java:1444) ~[?:1.21-DEV-7dfc70c]
        at net.minecraft.world.entity.Entity.move(Entity.java:1298) ~[?:1.21-DEV-7dfc70c]
        at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:3149) ~[?:1.21-DEV-7dfc70c]
        at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:3083) ~[?:1.21-DEV-7dfc70c]
        at net.minecraft.world.entity.player.Player.travel(Player.java:1731) ~[?:1.21-DEV-7dfc70c]
        at net.minecraft.server.level.ServerPlayer.travel(ServerPlayer.java:1930) ~[?:1.21-DEV-7dfc70c]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3615) ~[?:1.21-DEV-7dfc70c]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:613) ~[?:1.21-DEV-7dfc70c]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3263) ~[?:1.21-DEV-7dfc70c]
        at net.minecraft.world.entity.player.Player.tick(Player.java:317) ~[?:1.21-DEV-7dfc70c]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:888) ~[?:1.21-DEV-7dfc70c]
        ... 5 more
```

### Actions to reproduce (if known)

Have a large number of players on
Go through a nether portal

### Canvas version

Current Canvas Version: 1.21-DEV-7dfc70c (MC: 1.21)*
* You are running the latest version
Previous: 1.21-DEV-01a622a (MC: 1.21)

### Agreements

- [X] I am running the latest version of Canvas available from https://canvas.kesug.com/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by Canvas.

**Comment by Dueris** [comment]
mentioned in previous issue, same stacktrace
